package ai.whylabs.services.whylogs

import ai.whylabs.services.whylogs.core.config.IEnvVars
import ai.whylabs.services.whylogs.core.WhyLogsController
import ai.whylabs.services.whylogs.core.WhyLogsProfileManager
import ai.whylabs.services.whylogs.core.config.EnvVars
import ai.whylabs.services.whylogs.kafka.ConsumerController
import com.fasterxml.jackson.core.json.JsonReadFeature
import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.module.kotlin.jacksonMapperBuilder
import io.javalin.Javalin
import io.javalin.apibuilder.ApiBuilder.path
import io.javalin.apibuilder.ApiBuilder.post
import io.javalin.plugin.json.JavalinJackson
import io.javalin.plugin.openapi.OpenApiOptions
import io.javalin.plugin.openapi.OpenApiPlugin
import io.javalin.plugin.openapi.ui.SwaggerOptions
import io.sentry.Sentry
import io.sentry.SentryOptions
import io.swagger.v3.oas.models.info.Info
import kotlin.system.exitProcess
import org.slf4j.LoggerFactory

private val logger = LoggerFactory.getLogger("ai.whylabs.services.whylogs")
private val mapper = jacksonMapperBuilder()
    .enable(JsonReadFeature.ALLOW_NON_NUMERIC_NUMBERS) // Allows NaN
    .build().apply {
        // We ignore extra stuff because our `multiple` input can be generated by pandas.to_dict(orient"split), but
        // some extra info will be included in that dict as well, like `index`. Just ignore it rather than modeling it
        // or making people remove it before sending.
        configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
    }

fun main() {
    startServer()
}

fun startServer(envVars: IEnvVars = EnvVars.instance): Javalin = try {

    Sentry.init { options ->
        options.dsn = "https://123a444ad5d54c5fa1e92b6e7fd9f1ee@o1200382.ingest.sentry.io/6324335"
        // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
        // We recommend adjusting this value in production.
        options.tracesSampleRate = .2
        options.release = System.getProperty("RELEASE") ?: "local" // TODO inject container sha as env variable
        options.environment = System.getProperty("STAGE") ?: "development"
        // When first trying Sentry it's good to see what the SDK is doing:
        options.setDebug(true)
        options.cacheDirPath = "/tmp/sentry/"
        options.dsn = "http://key@2.localhost:9020/19"
//        options.proxy = SentryOptions.Proxy("localhost", "9020")
    }


    Thread.setDefaultUncaughtExceptionHandler { t, e ->
        Sentry.captureException(e, t.name)
    }

    val profileManager = WhyLogsProfileManager(envVars = envVars)
    if (envVars.kafkaConfig != null) {
        ConsumerController(envVars, profileManager)
    }
    val whylogs = WhyLogsController(envVars, profileManager)

    Javalin.create {
        it.registerPlugin(getConfiguredOpenApiPlugin())
        it.defaultContentType = "application/json"
        it.showJavalinBanner = false
        it.jsonMapper(JavalinJackson(mapper))
    }.apply {
        Runtime.getRuntime().addShutdownHook(Thread { stop() })
        before("logs", whylogs::preprocess)
        before("writeProfiles", whylogs::preprocess)

        exception(IllegalArgumentException::class.java) { e, ctx ->
            ctx.json(e.message ?: "Bad Request").status(400)
        }
        routes {
            path("logs") {
                post(whylogs::track)
            }
            path("writeProfiles") {
                post(whylogs::writeProfiles)
            }
        }
        after("logs", whylogs::after)
        // TODO make a call to list models to test the api key on startup as a health check
        logger.info("Checkout Swagger UI at http://localhost:${envVars.port}/swagger-ui")
        start(envVars.port)
    }
} catch (t: Throwable) {
    // Need to manually shut down here because our manager hooks itself up to runtime hooks
    // and starts a background thread. It would keep the JVM alive without javalin running.
    logger.error("Error starting up", t)
    exitProcess(1)
}

fun getConfiguredOpenApiPlugin() = OpenApiPlugin(
    OpenApiOptions(
        Info().apply {
            version("1.0")
            description("whylogs API")
        }
    ).apply {
        path("/swagger-docs") // endpoint for OpenAPI json
        swagger(SwaggerOptions("/swagger-ui")) // endpoint for swagger-ui
    }
)
