name: Docker Image CI

on:
  push:
    branches: [mainline]
  pull_request:
    branches: [mainline]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Build the Docker image
        run: docker build . --tag whylabs/whylogs:$GITHUB_SHA --tag whylabs/whylogs:latest

  publish_docker_image:
    name: Publish the Docker image to Docker Hub
    # if: ${{ !env.ACT }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        run: |
          docker push whylabs/whylogs:$GITHUB_SHA
          docker push whylabs/whylogs:latest
      - run: echo "Pushed whylabs/whylogs:$GITHUB_SHA"
