name: Workflow

on:
  push:
    branches: ["mainline"]
  pull_request:
    branches: "*"

jobs:
  build:
    name: Build Kotlin code and Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Build stuff
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
      - name: Ktlint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck
      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      # Docker stuff
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: whylabs/whylogs:${{ github.sha }}
          outputs: type=docker,dest=/tmp/whylogs-container.tar
      - name: Upload container artifact
        uses: actions/upload-artifact@v2
        with:
          name: container
          path: /tmp/whylogs-container.tar
      - name: Print container tag
        run: echo "Using tag ${{ github.sha }}"

  publish_docker_image:
    name: Publish the Docker image to Docker Hub
    if: ${{ !github.event.act && github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Download container artifact
        uses: actions/download-artifact@v2
        with:
          name: container
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/whylogs-container.tar
          docker image ls -a
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: whylabs/whylogs:${{ github.sha }}
