name: Build

on:
  push:
    branches: ["mainline"]
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Build stuff
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: installDist
      - name: Unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      # Docker stuff
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags:
            - whylabs/whylogs:$GITHUB_SHA
            - whylabs/whylogs:latest
      - name: Test container starts
        run: |
          docker run --rm whylabs/whylogs:$GITHUB_SHA

  publish_docker_image:
    name: Publish the Docker image to Docker Hub
    if: ${{ !env.ACT && github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags:
            - whylabs/whylogs:$GITHUB_SHA
            - whylabs/whylogs:latest
